import { createClient } from "@supabase/supabase-js";
import { projectId, publicAnonKey } from "../../utils/supabase/info";

// ─── Browser-side Supabase client (singleton) ─────────────────────────────────
// Used by all CRUD hooks and the API service layer.
// RLS (Row Level Security) is enforced server-side using the anon key;
// each operation requires an authenticated session to mutate data.
//
// P2.3 note: info.tsx is auto-generated by Figma Make and must not be
// committed with real secrets.  For a self-hosted deploy, replace the import
// above with:
//   const supabaseUrl  = import.meta.env.VITE_SUPABASE_URL;
//   const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
// and add VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY to your .env file.

const supabaseUrl = `https://${projectId}.supabase.co`;

export const supabase = createClient(supabaseUrl, publicAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// ─── Typed table names ────────────────────────────────────────────────────────
// Keep the list here so renaming a table only requires one change.
export const TABLES = {
  students:         "students",
  grades:           "student_grades",
  disciplineConfig: "discipline_config",
  documents:        "documents",
  terms:            "school_terms",
} as const;

// ─── Supabase Storage bucket ──────────────────────────────────────────────────
export const DOCUMENTS_BUCKET = "documents";
